FROM alpine:latest

ARG PB_VERSION=0.22.4

RUN apk add --no-cache wget unzip

RUN wget -q https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip \
    && unzip pocketbase_${PB_VERSION}_linux_amd64.zip \
    && rm pocketbase_${PB_VERSION}_linux_amd64.zip \
    && mv pocketbase /pb

EXPOSE 8090

CMD ["/pb", "serve", "--http=0.0.0.0:8090", "--dir=/pb_data"]